--- 
- name: reload systemd
  command: systemctl daemon-reload

- name: restart rclone
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - "rclone.service"
    - "rclone.timer"