---
- name: import docker's APT signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add Docker's repository ({{ ansible_distribution_release }})
  apt_repository:
    repo: deb [arch={{ linux_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: yes

- name: install docker package
  apt:
    name: [ "ca-certificates", "curl", "gnupg-agent", "software-properties-common", "docker-ce", "docker-ce-cli", "containerd.io" ]
    state: present
    update_cache: yes 
    cache_valid_time: 3600
  notify:
  - reload systemd

- name: download docker-compose
  include_tasks: install-docker-compose.yml
  when: docker_compose_install == True

- name: setup daemon.json
  template:
    src: daemon.json
    dest: "/etc/docker/"
    owner: "root"
    group: "root"
    mode: 0600
  ignore_errors: "{{ ansible_check_mode }}"

- name: start dockerd
  service:
    name: docker
    state: started
