---
#################################################
## S3 POC
#################################################

- hosts: stc-s3-poc
  become: true
  become_user: root

  roles:
  - { role: rclone,
      tags: [ 'rclone' ] }
  - { role: docker-service,
      docker_compose_install: true,
      tags: [ 'docker' ] }